name: Build Application and Make Release

on:
  push:
    tags:
      - '*'

jobs:

  build_release:
    name: Build Release
    uses: ./.github/workflows/build.yml
    with:
      build_type: Release

  create_release:
    needs: build_release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          path: 'Differential-source'
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Grab and store version
        run: |
          tag_name=$(echo ${{ github.ref }} | grep -oE "[^/]+$")
          echo "VERSION=$tag_name" >> $GITHUB_ENV
      - name: Package artifacts properly
        run: |
          mv ${{ github.workspace }}/Differential-source Differential-${{ env.VERSION }}
          mv Differential-Linux-Portable*/Differential-portable.tar.gz Differential-Linux-Portable-${{ env.VERSION }}.tar.gz
          mv Differential-Linux*/Differential.tar.gz Differential-Linux-${{ env.VERSION }}.tar.gz
          mv Differential-*.AppImage/Differential-*.AppImage Differential-Linux-${{ env.VERSION }}-x86_64.AppImage
          mv Differential-macOS*/Differential.tar.gz Differential-macOS-${{ env.VERSION }}.tar.gz

          tar -czf Differential-${{ env.VERSION }}.tar.gz Differential-${{ env.VERSION }}

          for d in Differential-Windows-*; do
            cd "${d}" || continue
            ARCH="$(echo -n ${d} | cut -d '-' -f 3)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="Differential-Windows-${ARCH}"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            zip -r -9 "../${NAME}-${{ env.VERSION }}.zip" *
            cd ..
          done

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Differential ${{ env.VERSION }}
          draft: true
          prerelease: false
          files: |
            Differential-Linux-${{ env.VERSION }}.tar.gz
            Differential-Linux-Portable-${{ env.VERSION }}.tar.gz
            Differential-Linux-${{ env.VERSION }}-x86_64.AppImage
            Differential-Windows-i686-${{ env.VERSION }}.zip
            Differential-Windows-i686-Portable-${{ env.VERSION }}.zip
            Differential-Windows-x86_64-${{ env.VERSION }}.zip
            Differential-Windows-x86_64-Portable-${{ env.VERSION }}.zip
            Differential-macOS-${{ env.VERSION }}.tar.gz
            Differential-${{ env.VERSION }}.tar.gz
